name: C++ Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt update && sudo apt install -y g++

    - name: Compile
      run: g++ -std=c++17 -o orderedSet Lab1.cpp

    - name: Run program (includes tests)
      run: ./orderedSet
